### ISSUE TITLE
Failures against (pre2.0) Django Master 

### ISSUE THREAD

**Issue by merwok** [django-crispy-forms/django-crispy-forms#687]
### Description:

Starting an app that includes django-crispy-forms gets these warnings:

```
venv/lib/python3.5/site-packages/crispy_forms/helper.py:4: RemovedInDjango20Warning: Importing from django.core.urlresolvers is deprecated in favor of django.urls.
  from django.core.urlresolvers import reverse, NoReverseMatch
```

```
venv/lib/python3.5/site-packages/crispy_forms/templatetags/crispy_forms_utils.py:19: RemovedInDjango20Warning: django.utils.functional.allow_lazy() is deprecated in favor of django.utils.functional.keep_lazy()
  remove_spaces = allow_lazy(remove_spaces, text_type)
```

**Comment by carltongibson** [comment]
1.11 build is now passing. We just have `master` (for 2.0) to deal with. There are the above plus a lot like this:

```
    def to_python(self, value):
>       value = value.strip()
E       AttributeError: 'list' object has no attribute 'strip'
```

https://travis-ci.org/django-crispy-forms/django-crispy-forms/jobs/203944846#L826

No doubt a single error. 

I don't think we're too far away.

**Comment by michael-k** [comment]
The mentioned `AttributeError` was caused by https://github.com/django/django/commit/af598187ecd9ddf398aa7a68a2b955599ddf3ae1.

**Comment by michael-k** [comment]
imho this can be closed

**Comment by carltongibson** [comment]
@michael-k Yep! Thanks for your awesome input on this!
