### ISSUE TITLE
_active_originally_included crashes with Field in Containers

### ISSUE THREAD

**Issue by Chris7** [django-crispy-forms/django-crispy-forms#526]
For instance, this code:

```
self.helper.layout = Layout(
            Accordion(
                Field('field1', wrapper_class='hide'),...
```

Will cause a crash because Field never sets the _active_originally_included attribute of the container.

**Comment by michaelkuty** [comment]
Same error for me after upgrading to 1.4 +

    'Field' object has no attribute '_active_originally_included'

    /srv/leonardo/sites/leonardo/local/lib/python2.7/site-packages/crispy_forms/bootstrap.py in open_target_group_for_form
            This is either the first group with errors or the first group
            in the container, unless that first group was originally set to
            active=False.
            """
            target = self.first_container_with_errors(form.errors.keys())
            if target is None:
                target = self.fields[0]
                            if not target._active_originally_included: ...
                    target.active = True
                return target
            target.active = True
            return target
    ▼ Local vars
    Variable	Value
    self	
    <crispy_forms.bootstrap.Accordion object at 0x7f9c757bba50>
    target	
    <crispy_forms.layout.Field object at 0x7f9c757bb7d0>
    form	
    <SearchForm bound=False, valid=False, fields=(q;models)>

**Comment by carltongibson** [comment]
OK. PRs welcome.
