### ISSUE TITLE
issue when update, 1.7.2 ==> 1.8.0+, AttributeError: 'NoneType' object has no attribute 'is_bound'

### ISSUE THREAD

**Issue by Saida07** [django-crispy-forms/django-crispy-forms#1009]
* Package version: 1.8.1
* Django version: 2.2.11
* Python version: 3.7

Thanks a lot for a very good package, I use it a lot, and really like it.
I wanted to update Crispy from 1.7.2 ==> 1.8.0+, but it raised an error (if I go back to version 1.7.2, it disappears).

I have tried to search for the fix, but cannot find it, thus I have a problem to debug it as I do not really understand the issue, can you please help.

I get the following error:

  File "//python3.7/site-packages/crispy_forms/templatetags/crispy_forms_tags.py", line 199, in render
    c = self.get_render(context).flatten()

  File "//python3.7/site-packages/crispy_forms/templatetags/crispy_forms_tags.py", line 111, in get_render
    node_context.update({'is_bound': actual_form.is_bound})
**AttributeError: 'NoneType' object has no attribute 'is_bound'**

**Comment by smithdc1** [comment]
Hi @Saida07 
It would be helpful if you could share a minimal solution which can be used to replicate the error. 
Also - have you tried git bisect to try and identify which commit causes this issue?

**Comment by smithdc1** [comment]
I finally came across this error myself. I managed to reproduce this error by something like this, and the important bit is that `TestModel` is a subclass of `models.Model` instead of `forms.ModelForm`.

``` python
def test_select():
    form = TestModel()
    form.helper = FormHelper()
    form.helper.layout = Layout("fruit")
    render_crispy_form(form)
```
Therefore I think this is an error due to trying to render a `Model` instead of a `ModelForm`. I'm going to close this issue on this basis, but if anyone thinks this is wrong and can produce an example that they think should work I'm happy to open it again.
